import { StyleSheet } from 'react-native';

export const colors = {
  background: '#FDFBF7',
  surface: '#FFFFFF',
  primary: '#404040',
  accent: '#7A8B73',
  accentDark: '#5C6B55',
  text: '#404040',
  textSecondary: '#555555',
  textMuted: '#7B7B7B',
  danger: '#FCA5A5',
  border: '#EAE5DD',
  borderLight: '#F4F0EB',
  glassBackground: 'rgba(255, 255, 255, 0.8)',
  glassBorder: '#EAE5DD',
  overlay: 'rgba(255,255,255,0.4)',
  skyBlue: '#E0F2FE',
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  formGroup: {
    marginBottom: 24,
  },
  headerStyle: {
    backgroundColor: colors.background,
    shadowColor: 'transparent',
    elevation: 0,
  },
  headerTitleStyle: {
    fontFamily: "BricolageGrotesque_500Medium",
    fontSize: 20,
  },
  scrollContent: {
    padding: 16,
  },
  header: {
    fontFamily: "BricolageGrotesque_500Medium",
    fontSize: 34,
    marginBottom: 8,
    textAlign: "center",
    color: colors.accent,
    letterSpacing: 0.5,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sectionPanel: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 12,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.text,
    textAlign: "left",
  },
  label: {
    fontFamily: "Besley_700Bold",
    fontSize: 13,
    marginBottom: 6,
    marginTop: 16,
    color: colors.textSecondary,
    letterSpacing: 0.5,
  },
  valueText: {
    fontFamily: "Besley_800ExtraBold",
    fontSize: 16,
    color: colors.text,
    marginBottom: 4,
  },
  attributeName: {
    fontFamily: "Besley_700Bold",
    color: "#999999",
    fontSize: 12,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  attributeValue: {
    fontFamily: "Besley_800ExtraBold",
    color: colors.text,
    fontSize: 16,
  },
  attributeValuePrimary: {
    fontFamily: "Besley_800ExtraBold",
    color: colors.primary,
    fontSize: 16,
  },
  input: {
    fontFamily: "Besley_600SemiBold",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: colors.text,
    backgroundColor: colors.surface,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  readOnlyLabel: {
    marginTop: 8,
    marginBottom: 2,
    color: "#999999",
    fontSize: 12,
    textTransform: "uppercase",
  },
  readOnlyInput: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    margin: 0,
    minHeight: 0,
    height: "auto",
    color: colors.text,
    shadowOpacity: 0,
    elevation: 0,
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
    paddingTop: 16,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    height: 52,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
    marginTop: 24,
  },
  primaryButtonText: {
    fontFamily: "Nunito_800ExtraBold",
    color: "#FFFFFF",
    fontSize: 16,
  },
  secondaryButton: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    height: 52,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 24,
  },
  secondaryButtonText: {
    fontFamily: "Nunito_800ExtraBold",
    color: colors.text,
    fontSize: 16,
  },
  dangerButton: {
    backgroundColor: colors.danger,
    height: 52,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  dangerButtonText: {
    fontFamily: "Nunito_800ExtraBold",
    color: "#FFFFFF",
    fontSize: 16,
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  backButtonText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    color: colors.text,
  },
  emptyText: {
    fontFamily: "Nunito_400Regular",
    fontSize: 14,
    color: colors.textMuted,
    fontStyle: "italic",
    marginTop: 5,
    marginBottom: 10,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
  },
  modalContent: {
    margin: 20,
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 24,
    maxHeight: "80%",
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 22,
    marginBottom: 16,
    textAlign: "center",
    color: colors.text,
  },
  listContainer: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
  },
  listItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  listTitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 20,
    color: colors.text,
  },
  itemTitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: colors.text,
    marginBottom: 4,
  },
});
